spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/original_frame?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
#  mvc:
#    throw-exception-if-no-handler-found: true

mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.weisean.dao
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
  # 加载全局的配置文件
  #configLocation: classpath:mybatis-config.xml
